# Generated by Django 6.1 on 2026-08-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='video_link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='preview',
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
