# Generated by Django 6.1 on 2026-08-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_course_owner_remove_lesson_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['id']},
        ),
    ]
